/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EAMAZONADS_AUTODEFS_H
#define S3EAMAZONADS_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_AMAZONADS_NAME "s3eAmazonAds"
#define S3E_EXT_AMAZONADS_HASH 0x8a4487ae

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("s3eAmazonAds", 16)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !S3EAMAZONADS_AUTODEFS_H */
